business_sim/app/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import home,register,logout_view,CreateBusinessView,create_business,room
from . import views
from django.contrib.auth import views as auth_views

app_name = 'app'

urlpatterns = [
    path('chat/',views.home,name='index'),
    path('<str:room_name>/',views.room,name='room'),
    path('user_login/',auth_views.LoginView.as_view(template_name='app/login.html',),name='user_login'),
    path('logout/',views.logout_view,name='logout'),
    path('register/',views.register,name='register'),
    path('create_business/',views.create_business,name='create_business'),
    # path('create_business/',views.CreateBusinessView.as_view(template_name='app/create_business.html'),name='create_business'),
]

business_sim/business_sim/urls.py
from django.contrib import admin
from django.urls import path,include
from app import views

urlpatterns = [
    path('',views.home,name='index'),
    path('admin/', admin.site.urls),
    path('app/',include('app.urls')),
]

business_sim/app/models.py
from django.db import models
import uuid
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.urls import reverse
from django.utils import timezone,timesince




# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,max_length=30)
    description = models.TextField(max_length=150)

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.user.username)
        super().save(*args, **kwargs)

@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
    else:
        instance.userprofile.save()


class Business(models.Model):
    name = models.CharField(max_length=100,unique=True)
    owner = models.ForeignKey(User,on_delete=models.CASCADE)
    description = models.TextField(max_length=400)
    stock_price = models.IntegerField(default=0)
    investors = models.ManyToManyField(User,related_name='investors')

    def get_absolute_url(self):
        return reverse('app:index')

    def __str__(self):
        return self.name

business_sim/app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from app.models import UserProfile,Business
from django.contrib.auth.models import User

class UserProfileForm(UserCreationForm):
    email = forms.EmailField(widget=forms.TextInput(
    attrs={'type': 'email',
           'placeholder':('Email')}))
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email']
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Username'}),
            'first_name': forms.TextInput(attrs={'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Last Name'}),
            'email': forms.TextInput(attrs={'placeholder': 'Email'}),
            
            }
        
    def clean(self):
        cleaned_data = super(UserProfileForm, self).clean()
        name = cleaned_data.get('username')
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')
        email = cleaned_data.get('email')
        password = cleaned_data.get('password')

class BusinessForm(forms.ModelForm):
    class Meta:
        model = Business
        fields = ['name','description']

    def clean(self):
        cleaned_data = super(BusinessForm,self).clean()
        name = cleaned_data.get('name')
        description = cleaned_data.get('description')

business_sim/app/views.py
from django.shortcuts import render
from .models import UserProfile,Business
from .forms import UserProfileForm,BusinessForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse,reverse_lazy
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
def home(request):
    return render(request,'app/index.html')

def room(request,room_name):
    return render(request,'app/room.html',{'room_name':room_name})

# register
def register(request):
    if request.method == "POST":
        form = UserProfileForm(request.POST)
        if form.is_valid():
            form.save()
            user = request.user
            username = form.cleaned_data.get('username')
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
    else:
        form = UserProfileForm()
    return render(request,'app/register.html',{'form':form})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
        
def create_business(request):
    if request.method == "POST":
        form = BusinessForm(request.POST)
        if form.is_valid():
            business = form.save(commit=False)
            business.owner = request.user
            business.save()
            return redirect('app:index')
    else:
        form = BusinessForm()
    
    return render(request,'app/create_business.html',{'form':form})

class CreateBusinessView(CreateView):
    model = Business
    login_url = reverse_lazy('app:user_login')
    redirect_field_name = 'app/index.html'
    form_class = BusinessForm
    def form_valid(self,form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

business_sim/app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Business Simulator</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <div class="navbar">
        <ul class="li-nav">
            <a href="{% url 'app:index' %}" id="navlink">Home</a>
            {% if user.is_authenticated %}
                <a href="{% url 'app:index' %}" id="navlink">{{ request.user }}</a>
            {% else %}
                <a href="{% url 'app:register' %}" id="navlink">Register</a>
            {% endif %}
            
        </ul>
    </div>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

business_sim/app/templates/app/create_business.html
{% extends 'app/base.html' %}

{% block content %}
    <h1>Create business</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
{% endblock %}

business_sim/app/templates/app/index.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}
    <h1>Business Simulator</h1>
    <h3>Chat room</h3>
    <input type="text" size="100" id="room-name-input"><br>
    <input type="button" value="Enter" id="room-name-submit">

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomname = document.querySelector('#room-name-input').value;
            window.location.pathname = '/app/' + roomname + '/'
        };
    </script>
{% endblock %}

business_sim/app/templates/app/login.html
{% extends 'app/base.html' %}

{% block content %}
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
    
{% endblock %}

business_sim/app/templates/app/register.html
{% extends 'app/base.html' %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
</form>
    
{% endblock %}

business_sim/app/templates/app/room.html
{% extends 'app/base.html' %}

{% block content %}
<textarea readonly id="chat-log" cols="100" rows="20"></textarea><br>
<input id="chat-message-input" type="text" size="100"><br>
<input id="chat-message-submit" type="button" value="Send">

<script>
var roomName = "{{ room_name|escapejs }}";

var chatSocket = new WebSocket(
    'ws://' + window.location.host +
    '/ws/chat/' + roomName + '/');

chatSocket.onmessage = function(e) {
    var data = JSON.parse(e.data);
    var message = data['message'];
    document.querySelector('#chat-log').value += (message + '\n');
};

chatSocket.onclose = function(e) {
    console.error('Chat socket closed unexpectedly');
};

document.querySelector('#chat-message-input').focus();
document.querySelector('#chat-message-input').onkeyup = function(e) {
    if (e.keyCode === 13) {  // enter, return
        document.querySelector('#chat-message-submit').click();
    }
};

document.querySelector('#chat-message-submit').onclick = function(e) {
    var messageInputDom = document.querySelector('#chat-message-input');
    var message = messageInputDom.value;
    chatSocket.send(JSON.stringify({
        'message': message
    }));

    messageInputDom.value = '';
};
</script>
{% endblock %}